services:
  db:
    container_name: taskflow_database
    image: postgres:16.3
    volumes:
      - taskflow_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=taskflow_database
    ports:
      - "5432:5432"

  pgAdmin: 
    depends_on:
      - db
    image: dpage/pgadmin4:8.6
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_PASSWORD=123456
      - PGADMIN_DEFAULT_EMAIL=user@google.com

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" 
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

volumes:
  taskflow_data:
  pgadmin_data:
